Repository cdktf/cdktf-cdk8s, pull requests merged in 2023-05, with the labels that each got.

#148 fix: make auto-approve actually work
  .github/workflows/auto-approve.yml
  .github/workflows/upgrade-main.yml
  .projenrc.ts
Labels: automerge

#144 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#149 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve, dependencies

#150 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve, dependencies

#151 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve, dependencies

#152 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve, dependencies

#153 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve, dependencies

#154 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve, dependencies

#155 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve, dependencies

#157 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve, dependencies
