Repository cdktf/cdktf-cdk8s, pull requests merged in 2023-08, with the labels that each got.

#196 chore(deps): upgrade dependencies
  .projen/tasks.json
  package.json
  yarn.lock
Labels: auto-approve, dependencies

#197 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve, dependencies

#198 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve, dependencies

#201 chore: automate upgrading cdktf itself
  .gitattributes
  .github/workflows/upgrade-cdktf.yml
  .gitignore
  .projen/files.json
  .projenrc.ts
  projenrc/upgrade-cdktf.ts
  scripts/update-cdktf.sh
Labels: auto-approve, automerge

#202 chore!: upgrade to cdktf 0.18.0
  .projen/deps.json
  .projenrc.ts
  package.json
  test/cdktf-cdk8s.test.ts
  yarn.lock
Labels: auto-approve, automerge, dependencies

#204 chore: remove API.md
  API.md
Labels: auto-approve, automerge

#203 chore: remove default pull request template
  .gitattributes
  .github/pull_request_template.md
  .gitignore
  .projen/files.json
  .projenrc.ts
Labels: auto-approve, automerge

#205 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve, automerge, dependencies

#207 chore: add compatibility info to README
  README.md
  scripts/update-cdktf.sh
Labels: auto-approve

#206 chore(ci): don't do a release on certain changes
  .github/workflows/release.yml
  .npmignore
  .projenrc.ts
Labels: auto-approve
