Repository cdktf/cdktf-cdk8s, pull requests merged in 2023-11, with the labels that each got.

#232 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve, automerge, dependencies

#233 chore(deps): upgrade dependencies
  .projen/deps.json
  .projen/tasks.json
  package.json
  yarn.lock
Labels: auto-approve, automerge, dependencies

#235 chore(deps): upgrade dependencies
  .github/workflows/auto-approve.yml
  .github/workflows/automerge.yml
  .github/workflows/build.yml
  .github/workflows/pull-request-lint.yml
  .github/workflows/release.yml
  .github/workflows/upgrade-cdktf.yml
  .github/workflows/upgrade-main.yml
  .projen/deps.json
  .projen/tasks.json
  .projenrc.ts
  package.json
  test/cdktf-cdk8s.test.ts
  yarn.lock
Labels: auto-approve, automerge

#236 chore(deps)!: increase minimum supported version of cdk8s to 2.8.0
  .projen/deps.json
  .projenrc.ts
  README.md
  package.json
  yarn.lock
Labels: auto-approve, automerge, dependencies, security

#234 chore(deps): upgrade dependencies
  .projen/deps.json
  .projen/tasks.json
  package.json
  yarn.lock
Labels: auto-approve, automerge, dependencies
