Repository cdktf/cdktf-cdk8s, pull requests merged in 2025-04, with the labels that each got.

#324 chore(ci): automate jsii & typescript updates
  .github/MAINTENANCE.md
  .github/workflows/upgrade-jsii-typescript.yml
  .projen/deps.json
  .projen/tasks.json
  .projenrc.ts
  package.json
  projenrc/upgrade-jsii-typescript.ts
  scripts/check-jsii-versions.js
  yarn.lock
Labels: auto-approve, automerge

#325 chore(deps): update pinned versions of GitHub Actions
  .github/workflows/build.yml
  .github/workflows/release.yml
  .github/workflows/upgrade-cdktf.yml
  .github/workflows/upgrade-jsii-typescript.yml
  .github/workflows/upgrade-main.yml
  .projenrc.ts
  projenrc/upgrade-cdktf.ts
Labels: auto-approve, automerge

#326 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve, automerge, dependencies

#327 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve, automerge, dependencies

#328 chore(deps): upgrade dependencies in examples
  .github/dependabot.yml
  examples/typescript/complex/package-lock.json
  examples/typescript/complex/package.json
  examples/typescript/hello-world/package-lock.json
  examples/typescript/hello-world/package.json
  scripts/update-cdktf.sh
Labels: auto-approve

#335 chore(deps): upgrade jsii & typescript to v5.6
  .github/workflows/upgrade-jsii-typescript.yml
  .projen/deps.json
  .projenrc.ts
  package.json
  yarn.lock
Labels: auto-approve, automerge, automated

#336 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve, automerge, dependencies

#343 chore(deps): upgrade dependencies
  package.json
  tsconfig.dev.json
  yarn.lock
Labels: auto-approve, automerge, dependencies
