Repository cdktf/cdktf-cdk8s, pull requests merged in 2025-01, with the labels that each got.

#306 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve, automerge, dependencies

#308 chore(ci): add workflow for upgrading jsii & typescript
  .gitattributes
  .github/workflows/upgrade-jsii-typescript.yml
  .gitignore
  .projen/deps.json
  .projen/files.json
  .projen/tasks.json
  .projenrc.ts
  package.json
  projenrc/upgrade-jsii-typescript.ts
  scripts/update-jsii-typescript.sh
  yarn.lock
Labels: auto-approve, automerge

#307 chore(deps): update pinned versions of GitHub Actions
  .github/workflows/auto-approve.yml
  .github/workflows/automerge.yml
  .github/workflows/build.yml
  .github/workflows/release.yml
  .github/workflows/upgrade-cdktf.yml
  .github/workflows/upgrade-main.yml
  .projenrc.ts
Labels: auto-approve, automerge

#309 chore: upgrade jsii & typescript to v5.5
  .github/workflows/upgrade-jsii-typescript.yml
  .projen/deps.json
  .projenrc.ts
  package.json
  yarn.lock
Labels: auto-approve, automerge, automated

#310 docs: create maintenance guide
  .github/MAINTENANCE.md
Labels: auto-approve, automerge

#311 chore(ci): update required version of constructs when cdktf is upgraded
  .github/MAINTENANCE.md
  .github/workflows/upgrade-cdktf.yml
  .projenrc.ts
  projenrc/upgrade-cdktf.ts
  scripts/update-cdktf.sh
Labels: auto-approve, automerge

#312 chore(deps): upgrade dependencies
  .projen/deps.json
  package.json
  yarn.lock
Labels: auto-approve, automerge, dependencies

#313 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve, automerge, dependencies

#314 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve, automerge, dependencies
